"""
Add comprehensive cells for Customer Satisfaction analysis
"""

import json

# Read the notebook
with open('Assignment_Session_1_Neural_Networks.ipynb', 'r') as f:
    notebook = json.load(f)

# Find the Customer satisfaction section
customer_idx = None
for i, cell in enumerate(notebook['cells']):
    if cell['cell_type'] == 'markdown' and 'Customer satisfaction' in ''.join(cell['source']):
        customer_idx = i + 1
        break

if customer_idx is None:
    print("Could not find Customer satisfaction section!")
    exit(1)

# Remove existing empty cells after the section if any
while customer_idx < len(notebook['cells']) and notebook['cells'][customer_idx]['cell_type'] == 'code':
    if not notebook['cells'][customer_idx].get('outputs') or len(notebook['cells'][customer_idx]['outputs']) == 0:
        if len(''.join(notebook['cells'][customer_idx].get('source', []))) < 100:
            notebook['cells'].pop(customer_idx)
            break
    else:
        break

# Define cells for customer satisfaction analysis
customer_cells = []

# Cell 1: Load and explore data
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 1. Data Loading and Exploration"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Load the dataset\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "dataset = pd.read_csv('./customersatisfaction.csv')\n",
        "\n",
        "print(\"Dataset shape:\", dataset.shape)\n",
        "print(\"\\nFirst few rows:\")\n",
        "print(dataset.head())\n",
        "\n",
        "print(\"\\nDataset info:\")\n",
        "print(dataset.info())\n",
        "\n",
        "print(\"\\nBasic statistics:\")\n",
        "print(dataset.describe())"
    ]
})

# Cell 2: Check balance and missing values
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 2. Data Quality Check: Balance and Missing Values"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Check for missing values\n",
        "print(\"Missing values per column:\")\n",
        "missing = dataset.isnull().sum()\n",
        "missing_pct = (missing / len(dataset)) * 100\n",
        "missing_df = pd.DataFrame({'Missing': missing, 'Percentage': missing_pct})\n",
        "missing_df = missing_df[missing_df['Missing'] > 0].sort_values('Missing', ascending=False)\n",
        "\n",
        "if len(missing_df) > 0:\n",
        "    print(missing_df)\n",
        "else:\n",
        "    print(\"✅ No missing values found!\")\n",
        "\n",
        "# Check class balance\n",
        "print(\"\\n\" + \"=\"*50)\n",
        "print(\"Class Distribution (TARGET):\")\n",
        "print(\"=\"*50)\n",
        "\n",
        "if 'TARGET' in dataset.columns:\n",
        "    target_counts = dataset['TARGET'].value_counts()\n",
        "    print(target_counts)\n",
        "    print(f\"\\nClass 0 (Satisfied): {target_counts[0]} ({target_counts[0]/len(dataset)*100:.2f}%)\")\n",
        "    print(f\"Class 1 (Unsatisfied): {target_counts[1]} ({target_counts[1]/len(dataset)*100:.2f}%)\")\n",
        "    \n",
        "    # Visualize\n",
        "    plt.figure(figsize=(10, 4))\n",
        "    \n",
        "    plt.subplot(1, 2, 1)\n",
        "    target_counts.plot(kind='bar', color=['green', 'red'])\n",
        "    plt.title('Class Distribution')\n",
        "    plt.xlabel('Class')\n",
        "    plt.ylabel('Count')\n",
        "    plt.xticks(rotation=0)\n",
        "    \n",
        "    plt.subplot(1, 2, 2)\n",
        "    plt.pie(target_counts, labels=['Satisfied (0)', 'Unsatisfied (1)'], \n",
        "            autopct='%1.1f%%', colors=['green', 'red'])\n",
        "    plt.title('Class Distribution (%)')\n",
        "    \n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    \n",
        "    # Check if imbalanced\n",
        "    imbalance_ratio = target_counts[0] / target_counts[1]\n",
        "    if imbalance_ratio > 3 or imbalance_ratio < 0.33:\n",
        "        print(f\"\\n⚠️ IMBALANCED DATASET! Ratio: {imbalance_ratio:.2f}:1\")\n",
        "        print(\"Consider using class weights or resampling techniques.\")\n",
        "    else:\n",
        "        print(f\"\\n✅ Dataset is relatively balanced. Ratio: {imbalance_ratio:.2f}:1\")\n",
        "else:\n",
        "    print(\"TARGET column not found!\")"
    ]
})

# Cell 3: Preprocessing
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 3. Data Preprocessing"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "\n",
        "# Separate features and target\n",
        "X = dataset.drop(['TARGET', 'ID'], axis=1, errors='ignore')\n",
        "y = dataset['TARGET']\n",
        "\n",
        "print(f\"Features shape: {X.shape}\")\n",
        "print(f\"Target shape: {y.shape}\")\n",
        "\n",
        "# Handle any remaining missing values\n",
        "if X.isnull().sum().sum() > 0:\n",
        "    print(\"\\nFilling missing values with median...\")\n",
        "    X = X.fillna(X.median())\n",
        "\n",
        "# Split data (test set of at least 10000 samples as required)\n",
        "X_train, X_test, y_train, y_test = train_test_split(\n",
        "    X, y, test_size=10000, random_state=42, stratify=y\n",
        ")\n",
        "\n",
        "print(f\"\\nTraining set: {X_train.shape}\")\n",
        "print(f\"Test set: {X_test.shape}\")\n",
        "\n",
        "# Standardize features\n",
        "scaler = StandardScaler()\n",
        "X_train_scaled = scaler.fit_transform(X_train)\n",
        "X_test_scaled = scaler.transform(X_test)\n",
        "\n",
        "print(\"\\n✅ Data preprocessing complete!\")"
    ]
})

# Cell 4: ML Algorithms comparison
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 4. Machine Learning Algorithms Comparison"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
        "from sklearn.svm import SVC\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "from sklearn.naive_bayes import GaussianNB\n",
        "from sklearn.metrics import accuracy_score, classification_report, roc_auc_score\n",
        "import time\n",
        "\n",
        "# Define ML models to test\n",
        "ml_models = {\n",
        "    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),\n",
        "    'Decision Tree': DecisionTreeClassifier(random_state=42),\n",
        "    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),\n",
        "    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42),\n",
        "    'K-Nearest Neighbors': KNeighborsClassifier(n_neighbors=5),\n",
        "    'Naive Bayes': GaussianNB()\n",
        "}\n",
        "\n",
        "ml_results = {}\n",
        "\n",
        "print(\"=\"*80)\n",
        "print(\"MACHINE LEARNING ALGORITHMS COMPARISON\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "for name, model in ml_models.items():\n",
        "    print(f\"\\nTraining {name}...\")\n",
        "    \n",
        "    # Training time\n",
        "    start_time = time.time()\n",
        "    model.fit(X_train_scaled, y_train)\n",
        "    train_time = time.time() - start_time\n",
        "    \n",
        "    # Prediction time\n",
        "    start_time = time.time()\n",
        "    y_pred = model.predict(X_test_scaled)\n",
        "    pred_time = time.time() - start_time\n",
        "    \n",
        "    # Metrics\n",
        "    accuracy = accuracy_score(y_test, y_pred)\n",
        "    \n",
        "    # ROC AUC (if model supports predict_proba)\n",
        "    try:\n",
        "        y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]\n",
        "        roc_auc = roc_auc_score(y_test, y_pred_proba)\n",
        "    except:\n",
        "        roc_auc = None\n",
        "    \n",
        "    ml_results[name] = {\n",
        "        'accuracy': accuracy,\n",
        "        'roc_auc': roc_auc,\n",
        "        'train_time': train_time,\n",
        "        'pred_time': pred_time\n",
        "    }\n",
        "    \n",
        "    print(f\"  Accuracy: {accuracy:.4f}\")\n",
        "    if roc_auc:\n",
        "        print(f\"  ROC AUC: {roc_auc:.4f}\")\n",
        "    print(f\"  Training time: {train_time:.3f}s\")\n",
        "    print(f\"  Prediction time: {pred_time:.3f}s\")\n",
        "\n",
        "# Summary table\n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"SUMMARY\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "ml_summary = pd.DataFrame(ml_results).T\n",
        "ml_summary = ml_summary.sort_values('accuracy', ascending=False)\n",
        "print(ml_summary)\n",
        "\n",
        "# Visualize results\n",
        "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
        "\n",
        "# Accuracy comparison\n",
        "ml_summary['accuracy'].plot(kind='barh', ax=axes[0], color='skyblue')\n",
        "axes[0].set_xlabel('Accuracy')\n",
        "axes[0].set_title('Model Accuracy Comparison')\n",
        "axes[0].grid(True, axis='x')\n",
        "\n",
        "# Training time comparison\n",
        "ml_summary['train_time'].plot(kind='barh', ax=axes[1], color='orange')\n",
        "axes[1].set_xlabel('Training Time (seconds)')\n",
        "axes[1].set_title('Training Time Comparison')\n",
        "axes[1].grid(True, axis='x')\n",
        "\n",
        "# Prediction time comparison\n",
        "ml_summary['pred_time'].plot(kind='barh', ax=axes[2], color='green')\n",
        "axes[2].set_xlabel('Prediction Time (seconds)')\n",
        "axes[2].set_title('Prediction Speed Comparison')\n",
        "axes[2].grid(True, axis='x')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "best_ml_model = ml_summary.index[0]\n",
        "print(f\"\\n🏆 Best ML Model: {best_ml_model}\")\n",
        "print(f\"   Accuracy: {ml_summary.loc[best_ml_model, 'accuracy']:.4f}\")"
    ]
})

# Cell 5: Neural Network - Baseline
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 5. Neural Network - Baseline Model"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "import tensorflow as tf\n",
        "from tensorflow.keras.models import Sequential\n",
        "from tensorflow.keras.layers import Dense, Dropout, BatchNormalization\n",
        "from tensorflow.keras.callbacks import EarlyStopping\n",
        "\n",
        "# Baseline neural network\n",
        "print(\"Building baseline neural network...\")\n",
        "\n",
        "baseline_nn = Sequential([\n",
        "    Dense(64, input_dim=X_train_scaled.shape[1], activation='relu'),\n",
        "    Dense(32, activation='relu'),\n",
        "    Dense(1, activation='sigmoid')\n",
        "])\n",
        "\n",
        "baseline_nn.compile(\n",
        "    optimizer='adam',\n",
        "    loss='binary_crossentropy',\n",
        "    metrics=['accuracy']\n",
        ")\n",
        "\n",
        "print(baseline_nn.summary())\n",
        "\n",
        "# Train\n",
        "print(\"\\nTraining baseline model...\")\n",
        "start_time = time.time()\n",
        "\n",
        "history_baseline = baseline_nn.fit(\n",
        "    X_train_scaled, y_train,\n",
        "    validation_split=0.2,\n",
        "    epochs=50,\n",
        "    batch_size=256,\n",
        "    verbose=1,\n",
        "    callbacks=[EarlyStopping(patience=5, restore_best_weights=True)]\n",
        ")\n",
        "\n",
        "train_time_nn = time.time() - start_time\n",
        "\n",
        "# Evaluate\n",
        "start_time = time.time()\n",
        "y_pred_nn = (baseline_nn.predict(X_test_scaled) > 0.5).astype(int)\n",
        "pred_time_nn = time.time() - start_time\n",
        "\n",
        "accuracy_nn = accuracy_score(y_test, y_pred_nn)\n",
        "y_pred_proba_nn = baseline_nn.predict(X_test_scaled)\n",
        "roc_auc_nn = roc_auc_score(y_test, y_pred_proba_nn)\n",
        "\n",
        "print(f\"\\nBaseline NN Results:\")\n",
        "print(f\"  Accuracy: {accuracy_nn:.4f}\")\n",
        "print(f\"  ROC AUC: {roc_auc_nn:.4f}\")\n",
        "print(f\"  Training time: {train_time_nn:.3f}s\")\n",
        "print(f\"  Prediction time: {pred_time_nn:.3f}s\")\n",
        "\n",
        "# Plot training history\n",
        "plt.figure(figsize=(12, 4))\n",
        "\n",
        "plt.subplot(1, 2, 1)\n",
        "plt.plot(history_baseline.history['accuracy'], label='Train')\n",
        "plt.plot(history_baseline.history['val_accuracy'], label='Validation')\n",
        "plt.xlabel('Epoch')\n",
        "plt.ylabel('Accuracy')\n",
        "plt.title('Baseline NN - Accuracy')\n",
        "plt.legend()\n",
        "plt.grid(True)\n",
        "\n",
        "plt.subplot(1, 2, 2)\n",
        "plt.plot(history_baseline.history['loss'], label='Train')\n",
        "plt.plot(history_baseline.history['val_loss'], label='Validation')\n",
        "plt.xlabel('Epoch')\n",
        "plt.ylabel('Loss')\n",
        "plt.title('Baseline NN - Loss')\n",
        "plt.legend()\n",
        "plt.grid(True)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# Cell 6: Neural Network - Hyperparameter Tuning
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 6. Neural Network - Hyperparameter Tuning"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Test different NN configurations\n",
        "print(\"=\"*80)\n",
        "print(\"NEURAL NETWORK HYPERPARAMETER TUNING\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "nn_configs = [\n",
        "    {\n",
        "        'name': 'Baseline',\n",
        "        'layers': [64, 32],\n",
        "        'dropout': 0.0,\n",
        "        'batch_norm': False,\n",
        "        'learning_rate': 0.001\n",
        "    },\n",
        "    {\n",
        "        'name': 'Deep Network',\n",
        "        'layers': [128, 64, 32, 16],\n",
        "        'dropout': 0.3,\n",
        "        'batch_norm': True,\n",
        "        'learning_rate': 0.001\n",
        "    },\n",
        "    {\n",
        "        'name': 'Wide Network',\n",
        "        'layers': [256, 128],\n",
        "        'dropout': 0.4,\n",
        "        'batch_norm': True,\n",
        "        'learning_rate': 0.001\n",
        "    },\n",
        "    {\n",
        "        'name': 'Optimized',\n",
        "        'layers': [128, 64, 32],\n",
        "        'dropout': 0.3,\n",
        "        'batch_norm': True,\n",
        "        'learning_rate': 0.0005\n",
        "    }\n",
        "]\n",
        "\n",
        "nn_results = {}\n",
        "\n",
        "for config in nn_configs:\n",
        "    print(f\"\\nTesting: {config['name']}\")\n",
        "    print(f\"  Architecture: {config['layers']}\")\n",
        "    print(f\"  Dropout: {config['dropout']}, BatchNorm: {config['batch_norm']}\")\n",
        "    \n",
        "    # Build model\n",
        "    model = Sequential()\n",
        "    \n",
        "    # First layer\n",
        "    model.add(Dense(config['layers'][0], input_dim=X_train_scaled.shape[1], \n",
        "                   activation='relu', kernel_initializer='he_uniform'))\n",
        "    if config['batch_norm']:\n",
        "        model.add(BatchNormalization())\n",
        "    if config['dropout'] > 0:\n",
        "        model.add(Dropout(config['dropout']))\n",
        "    \n",
        "    # Hidden layers\n",
        "    for neurons in config['layers'][1:]:\n",
        "        model.add(Dense(neurons, activation='relu', kernel_initializer='he_uniform'))\n",
        "        if config['batch_norm']:\n",
        "            model.add(BatchNormalization())\n",
        "        if config['dropout'] > 0:\n",
        "            model.add(Dropout(config['dropout']))\n",
        "    \n",
        "    # Output layer\n",
        "    model.add(Dense(1, activation='sigmoid'))\n",
        "    \n",
        "    # Compile\n",
        "    optimizer = tf.keras.optimizers.Adam(learning_rate=config['learning_rate'])\n",
        "    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])\n",
        "    \n",
        "    # Train\n",
        "    start_time = time.time()\n",
        "    history = model.fit(\n",
        "        X_train_scaled, y_train,\n",
        "        validation_split=0.2,\n",
        "        epochs=50,\n",
        "        batch_size=256,\n",
        "        verbose=0,\n",
        "        callbacks=[EarlyStopping(patience=5, restore_best_weights=True)]\n",
        "    )\n",
        "    train_time = time.time() - start_time\n",
        "    \n",
        "    # Evaluate\n",
        "    start_time = time.time()\n",
        "    y_pred_proba = model.predict(X_test_scaled, verbose=0)\n",
        "    pred_time = time.time() - start_time\n",
        "    \n",
        "    y_pred = (y_pred_proba > 0.5).astype(int)\n",
        "    accuracy = accuracy_score(y_test, y_pred)\n",
        "    roc_auc = roc_auc_score(y_test, y_pred_proba)\n",
        "    \n",
        "    nn_results[config['name']] = {\n",
        "        'accuracy': accuracy,\n",
        "        'roc_auc': roc_auc,\n",
        "        'train_time': train_time,\n",
        "        'pred_time': pred_time,\n",
        "        'history': history.history,\n",
        "        'params': model.count_params()\n",
        "    }\n",
        "    \n",
        "    print(f\"  Accuracy: {accuracy:.4f}\")\n",
        "    print(f\"  ROC AUC: {roc_auc:.4f}\")\n",
        "    print(f\"  Training time: {train_time:.3f}s\")\n",
        "    print(f\"  Parameters: {model.count_params():,}\")\n",
        "\n",
        "# Summary\n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"NEURAL NETWORK RESULTS SUMMARY\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "nn_summary = pd.DataFrame({\n",
        "    name: {\n",
        "        'Accuracy': results['accuracy'],\n",
        "        'ROC AUC': results['roc_auc'],\n",
        "        'Train Time': results['train_time'],\n",
        "        'Parameters': results['params']\n",
        "    }\n",
        "    for name, results in nn_results.items()\n",
        "}).T\n",
        "\n",
        "nn_summary = nn_summary.sort_values('Accuracy', ascending=False)\n",
        "print(nn_summary)\n",
        "\n",
        "# Plot comparison\n",
        "fig, axes = plt.subplots(2, 2, figsize=(15, 10))\n",
        "\n",
        "# Accuracy\n",
        "nn_summary['Accuracy'].plot(kind='barh', ax=axes[0, 0], color='skyblue')\n",
        "axes[0, 0].set_xlabel('Accuracy')\n",
        "axes[0, 0].set_title('NN Accuracy Comparison')\n",
        "axes[0, 0].grid(True, axis='x')\n",
        "\n",
        "# ROC AUC\n",
        "nn_summary['ROC AUC'].plot(kind='barh', ax=axes[0, 1], color='lightgreen')\n",
        "axes[0, 1].set_xlabel('ROC AUC')\n",
        "axes[0, 1].set_title('NN ROC AUC Comparison')\n",
        "axes[0, 1].grid(True, axis='x')\n",
        "\n",
        "# Training curves for best model\n",
        "best_nn = nn_summary.index[0]\n",
        "best_history = nn_results[best_nn]['history']\n",
        "\n",
        "axes[1, 0].plot(best_history['accuracy'], label='Train')\n",
        "axes[1, 0].plot(best_history['val_accuracy'], label='Validation')\n",
        "axes[1, 0].set_xlabel('Epoch')\n",
        "axes[1, 0].set_ylabel('Accuracy')\n",
        "axes[1, 0].set_title(f'Best Model ({best_nn}) - Accuracy')\n",
        "axes[1, 0].legend()\n",
        "axes[1, 0].grid(True)\n",
        "\n",
        "axes[1, 1].plot(best_history['loss'], label='Train')\n",
        "axes[1, 1].plot(best_history['val_loss'], label='Validation')\n",
        "axes[1, 1].set_xlabel('Epoch')\n",
        "axes[1, 1].set_ylabel('Loss')\n",
        "axes[1, 1].set_title(f'Best Model ({best_nn}) - Loss')\n",
        "axes[1, 1].legend()\n",
        "axes[1, 1].grid(True)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(f\"\\n🏆 Best Neural Network: {best_nn}\")\n",
        "print(f\"   Accuracy: {nn_summary.loc[best_nn, 'Accuracy']:.4f}\")\n",
        "print(f\"   ROC AUC: {nn_summary.loc[best_nn, 'ROC AUC']:.4f}\")"
    ]
})

# Cell 7: Final Comparison and Conclusions
customer_cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### 7. Final Comparison: ML vs Neural Networks"
    ]
})

customer_cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "print(\"=\"*80)\n",
        "print(\"FINAL COMPARISON: MACHINE LEARNING vs NEURAL NETWORKS\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "# Combine results\n",
        "all_results = {}\n",
        "\n",
        "# Add ML results\n",
        "for name, results in ml_results.items():\n",
        "    all_results[f\"ML: {name}\"] = results\n",
        "\n",
        "# Add NN results\n",
        "for name, results in nn_results.items():\n",
        "    all_results[f\"NN: {name}\"] = {\n",
        "        'accuracy': results['accuracy'],\n",
        "        'roc_auc': results['roc_auc'],\n",
        "        'train_time': results['train_time'],\n",
        "        'pred_time': results['pred_time']\n",
        "    }\n",
        "\n",
        "# Create comparison dataframe\n",
        "comparison_df = pd.DataFrame(all_results).T\n",
        "comparison_df = comparison_df.sort_values('accuracy', ascending=False)\n",
        "\n",
        "print(\"\\nTop 10 Models by Accuracy:\")\n",
        "print(comparison_df.head(10))\n",
        "\n",
        "# Visualize\n",
        "fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n",
        "\n",
        "# Accuracy comparison\n",
        "comparison_df['accuracy'].head(10).plot(kind='barh', ax=axes[0, 0], \n",
        "                                        color=['red' if 'ML' in x else 'blue' \n",
        "                                               for x in comparison_df.head(10).index])\n",
        "axes[0, 0].set_xlabel('Accuracy')\n",
        "axes[0, 0].set_title('Top 10 Models - Accuracy')\n",
        "axes[0, 0].grid(True, axis='x')\n",
        "\n",
        "# ROC AUC comparison\n",
        "roc_data = comparison_df.dropna(subset=['roc_auc'])['roc_auc'].head(10)\n",
        "roc_data.plot(kind='barh', ax=axes[0, 1],\n",
        "              color=['red' if 'ML' in x else 'blue' for x in roc_data.index])\n",
        "axes[0, 1].set_xlabel('ROC AUC')\n",
        "axes[0, 1].set_title('Top 10 Models - ROC AUC')\n",
        "axes[0, 1].grid(True, axis='x')\n",
        "\n",
        "# Training time comparison\n",
        "comparison_df['train_time'].head(10).plot(kind='barh', ax=axes[1, 0],\n",
        "                                          color=['red' if 'ML' in x else 'blue' \n",
        "                                                 for x in comparison_df.head(10).index])\n",
        "axes[1, 0].set_xlabel('Training Time (seconds)')\n",
        "axes[1, 0].set_title('Top 10 Models - Training Time')\n",
        "axes[1, 0].grid(True, axis='x')\n",
        "\n",
        "# Prediction time comparison\n",
        "comparison_df['pred_time'].head(10).plot(kind='barh', ax=axes[1, 1],\n",
        "                                         color=['red' if 'ML' in x else 'blue' \n",
        "                                                for x in comparison_df.head(10).index])\n",
        "axes[1, 1].set_xlabel('Prediction Time (seconds)')\n",
        "axes[1, 1].set_title('Top 10 Models - Prediction Speed')\n",
        "axes[1, 1].grid(True, axis='x')\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Statistics\n",
        "ml_mask = comparison_df.index.str.contains('ML:')\n",
        "nn_mask = comparison_df.index.str.contains('NN:')\n",
        "\n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"CONCLUSIONS\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "print(\"\\n📊 ACCURACY:\")\n",
        "print(f\"  ML Average: {comparison_df[ml_mask]['accuracy'].mean():.4f}\")\n",
        "print(f\"  NN Average: {comparison_df[nn_mask]['accuracy'].mean():.4f}\")\n",
        "print(f\"  Best ML: {comparison_df[ml_mask]['accuracy'].max():.4f}\")\n",
        "print(f\"  Best NN: {comparison_df[nn_mask]['accuracy'].max():.4f}\")\n",
        "\n",
        "print(\"\\n⚡ SPEED (Training):\")\n",
        "print(f\"  ML Average: {comparison_df[ml_mask]['train_time'].mean():.3f}s\")\n",
        "print(f\"  NN Average: {comparison_df[nn_mask]['train_time'].mean():.3f}s\")\n",
        "print(f\"  Fastest ML: {comparison_df[ml_mask]['train_time'].min():.3f}s\")\n",
        "print(f\"  Fastest NN: {comparison_df[nn_mask]['train_time'].min():.3f}s\")\n",
        "\n",
        "print(\"\\n⚡ SPEED (Prediction):\")\n",
        "print(f\"  ML Average: {comparison_df[ml_mask]['pred_time'].mean():.3f}s\")\n",
        "print(f\"  NN Average: {comparison_df[nn_mask]['pred_time'].mean():.3f}s\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"KEY FINDINGS:\")\n",
        "print(\"=\"*80)\n",
        "\n",
        "best_overall = comparison_df.index[0]\n",
        "print(f\"\\n🏆 BEST OVERALL MODEL: {best_overall}\")\n",
        "print(f\"   Accuracy: {comparison_df.loc[best_overall, 'accuracy']:.4f}\")\n",
        "print(f\"   ROC AUC: {comparison_df.loc[best_overall, 'roc_auc']:.4f}\")\n",
        "print(f\"   Training Time: {comparison_df.loc[best_overall, 'train_time']:.3f}s\")\n",
        "\n",
        "print(\"\\n📝 SUMMARY:\")\n",
        "if comparison_df[nn_mask]['accuracy'].max() > comparison_df[ml_mask]['accuracy'].max():\n",
        "    print(\"  ✅ Neural Networks achieved higher accuracy\")\n",
        "else:\n",
        "    print(\"  ✅ Traditional ML achieved higher accuracy\")\n",
        "\n",
        "if comparison_df[ml_mask]['train_time'].mean() < comparison_df[nn_mask]['train_time'].mean():\n",
        "    print(\"  ✅ Traditional ML is faster to train\")\n",
        "else:\n",
        "    print(\"  ✅ Neural Networks are faster to train\")\n",
        "\n",
        "print(\"\\n  📌 Traditional ML (Random Forest, Gradient Boosting):\")\n",
        "print(\"     - Faster training on small/medium datasets\")\n",
        "print(\"     - Less hyperparameter tuning required\")\n",
        "print(\"     - More interpretable\")\n",
        "print(\"     - Good baseline performance\")\n",
        "\n",
        "print(\"\\n  📌 Neural Networks:\")\n",
        "print(\"     - Can achieve higher accuracy with proper tuning\")\n",
        "print(\"     - Better at capturing complex patterns\")\n",
        "print(\"     - Require more data and tuning\")\n",
        "print(\"     - Longer training time but scalable\")\n",
        "\n",
        "print(\"\\n✅ Analysis complete!\")"
    ]
})

# Insert all cells
for i, cell in enumerate(customer_cells):
    notebook['cells'].insert(customer_idx + i, cell)

# Save
with open('Assignment_Session_1_Neural_Networks.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print(f"✅ Successfully added {len(customer_cells)} cells for Customer Satisfaction analysis!")
print(f"   Inserted at position {customer_idx}")
print("\\nThe cells cover:")
print("   1. Data loading and exploration")
print("   2. Balance and missing value checks")
print("   3. Data preprocessing")
print("   4. ML algorithms comparison")
print("   5. Baseline neural network")
print("   6. NN hyperparameter tuning")
print("   7. Final comparison and conclusions")
